kind: pipeline
name: default

steps:
- name: build
  image: golang:1.13
  commands:
  - make build_linux_amd64

- name: docker
  image: plugins/docker
  settings:
    registry: registry.hub.docker.com
    repo: registry.hub.docker.com/dhso/cors-anywhere
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
